// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: doxchain/oauthtwo/v1beta1/authorization_code_registry.proto

package types

import (
	fmt "fmt"
	types "github.com/be-heroes/doxchain/x/did/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AuthorizationCodeRegistry struct {
	Owner types.Did                        `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner"`
	Codes []AuthorizationCodeRegistryEntry `protobuf:"bytes,2,rep,name=codes,proto3" json:"codes"`
}

func (m *AuthorizationCodeRegistry) Reset()         { *m = AuthorizationCodeRegistry{} }
func (m *AuthorizationCodeRegistry) String() string { return proto.CompactTextString(m) }
func (*AuthorizationCodeRegistry) ProtoMessage()    {}
func (*AuthorizationCodeRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca24fecae0820e66, []int{0}
}
func (m *AuthorizationCodeRegistry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuthorizationCodeRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuthorizationCodeRegistry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuthorizationCodeRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationCodeRegistry.Merge(m, src)
}
func (m *AuthorizationCodeRegistry) XXX_Size() int {
	return m.Size()
}
func (m *AuthorizationCodeRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationCodeRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationCodeRegistry proto.InternalMessageInfo

func (m *AuthorizationCodeRegistry) GetOwner() types.Did {
	if m != nil {
		return m.Owner
	}
	return types.Did{}
}

func (m *AuthorizationCodeRegistry) GetCodes() []AuthorizationCodeRegistryEntry {
	if m != nil {
		return m.Codes
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthorizationCodeRegistry)(nil), "beheroes.doxchain.oauthtwo.v1beta1.AuthorizationCodeRegistry")
}

func init() {
	proto.RegisterFile("doxchain/oauthtwo/v1beta1/authorization_code_registry.proto", fileDescriptor_ca24fecae0820e66)
}

var fileDescriptor_ca24fecae0820e66 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd0, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x07, 0xf0, 0x18, 0x28, 0x43, 0xba, 0x45, 0x0c, 0x25, 0x83, 0xa9, 0x32, 0x75, 0xe1, 0xac,
	0x96, 0x11, 0x09, 0xa9, 0x01, 0x24, 0xe6, 0x8e, 0x0c, 0x44, 0x49, 0x7c, 0x4a, 0x3c, 0x90, 0xab,
	0x1c, 0x97, 0xb6, 0x3c, 0x05, 0xef, 0xc3, 0x0b, 0x74, 0xec, 0xc8, 0x84, 0x50, 0xf2, 0x22, 0x28,
	0x9f, 0x20, 0x21, 0x84, 0xc4, 0x66, 0xcb, 0xbe, 0xdf, 0xdd, 0xfd, 0xed, 0x4b, 0x49, 0x9b, 0x38,
	0x0d, 0x55, 0x26, 0x28, 0x5c, 0x99, 0xd4, 0xac, 0x49, 0x3c, 0x4d, 0x23, 0x34, 0xe1, 0x54, 0x54,
	0x77, 0xd2, 0xea, 0x39, 0x34, 0x8a, 0xb2, 0x20, 0x26, 0x89, 0x81, 0xc6, 0x44, 0xe5, 0x46, 0x6f,
	0x61, 0xa9, 0xc9, 0x90, 0xe3, 0x45, 0x98, 0xa2, 0x26, 0xcc, 0xa1, 0x53, 0xa0, 0x53, 0xa0, 0x55,
	0xdc, 0x93, 0x84, 0x12, 0xaa, 0xbf, 0x8b, 0xea, 0xd4, 0x54, 0xba, 0xf3, 0x7f, 0xb5, 0x0d, 0x30,
	0xeb, 0x9b, 0xbb, 0xbc, 0x27, 0xa4, 0x92, 0x7d, 0xb5, 0x54, 0xb2, 0x79, 0xf7, 0x5e, 0x99, 0x7d,
	0x3a, 0xff, 0x6e, 0x5d, 0x93, 0xc4, 0x45, 0x2b, 0x39, 0x57, 0xf6, 0x80, 0xd6, 0x19, 0xea, 0x11,
	0x1b, 0xb3, 0xc9, 0x70, 0xe6, 0xc1, 0xcf, 0x55, 0x2a, 0xaa, 0x65, 0xe1, 0x46, 0x49, 0xff, 0x68,
	0xf7, 0x7e, 0x66, 0x2d, 0x9a, 0x32, 0xe7, 0xc1, 0x1e, 0x54, 0xa3, 0xe5, 0xa3, 0x83, 0xf1, 0xe1,
	0x64, 0x38, 0xf3, 0xe1, 0xef, 0x28, 0xe0, 0xd7, 0x69, 0x6e, 0xab, 0xb5, 0x3a, 0xbf, 0x66, 0xfd,
	0xbb, 0x5d, 0xc1, 0xd9, 0xbe, 0xe0, 0xec, 0xa3, 0xe0, 0xec, 0xa5, 0xe4, 0xd6, 0xbe, 0xe4, 0xd6,
	0x5b, 0xc9, 0xad, 0x7b, 0x48, 0x94, 0x49, 0x57, 0x11, 0xc4, 0xf4, 0x28, 0x22, 0x3c, 0x6f, 0xba,
	0x8a, 0x3e, 0x8c, 0xcd, 0x57, 0xa2, 0x66, 0xbb, 0xc4, 0x3c, 0x3a, 0xae, 0xe3, 0xb8, 0xf8, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0x85, 0x95, 0x34, 0x8e, 0xea, 0x01, 0x00, 0x00,
}

func (m *AuthorizationCodeRegistry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthorizationCodeRegistry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuthorizationCodeRegistry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Codes) > 0 {
		for iNdEx := len(m.Codes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Codes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuthorizationCodeRegistry(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Owner.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAuthorizationCodeRegistry(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintAuthorizationCodeRegistry(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuthorizationCodeRegistry(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AuthorizationCodeRegistry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Owner.Size()
	n += 1 + l + sovAuthorizationCodeRegistry(uint64(l))
	if len(m.Codes) > 0 {
		for _, e := range m.Codes {
			l = e.Size()
			n += 1 + l + sovAuthorizationCodeRegistry(uint64(l))
		}
	}
	return n
}

func sovAuthorizationCodeRegistry(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuthorizationCodeRegistry(x uint64) (n int) {
	return sovAuthorizationCodeRegistry(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AuthorizationCodeRegistry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthorizationCodeRegistry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthorizationCodeRegistry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthorizationCodeRegistry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorizationCodeRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthorizationCodeRegistry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorizationCodeRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Owner.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Codes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthorizationCodeRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthorizationCodeRegistry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthorizationCodeRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Codes = append(m.Codes, AuthorizationCodeRegistryEntry{})
			if err := m.Codes[len(m.Codes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthorizationCodeRegistry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthorizationCodeRegistry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuthorizationCodeRegistry(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuthorizationCodeRegistry
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthorizationCodeRegistry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthorizationCodeRegistry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuthorizationCodeRegistry
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuthorizationCodeRegistry
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuthorizationCodeRegistry
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuthorizationCodeRegistry        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuthorizationCodeRegistry          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuthorizationCodeRegistry = fmt.Errorf("proto: unexpected end of group")
)
