// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: doxchain/did/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateDidRequest struct {
	Did Did `protobuf:"bytes,1,opt,name=did,proto3" json:"did"`
}

func (m *MsgCreateDidRequest) Reset()         { *m = MsgCreateDidRequest{} }
func (m *MsgCreateDidRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDidRequest) ProtoMessage()    {}
func (*MsgCreateDidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{0}
}
func (m *MsgCreateDidRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateDidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateDidRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateDidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDidRequest.Merge(m, src)
}
func (m *MsgCreateDidRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateDidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDidRequest proto.InternalMessageInfo

func (m *MsgCreateDidRequest) GetDid() Did {
	if m != nil {
		return m.Did
	}
	return Did{}
}

type MsgCreateDidResponse struct {
	FullyQualifiedDidIdentifier string `protobuf:"bytes,1,opt,name=fullyQualifiedDidIdentifier,proto3" json:"fullyQualifiedDidIdentifier,omitempty"`
}

func (m *MsgCreateDidResponse) Reset()         { *m = MsgCreateDidResponse{} }
func (m *MsgCreateDidResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDidResponse) ProtoMessage()    {}
func (*MsgCreateDidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{1}
}
func (m *MsgCreateDidResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateDidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateDidResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateDidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDidResponse.Merge(m, src)
}
func (m *MsgCreateDidResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateDidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDidResponse proto.InternalMessageInfo

func (m *MsgCreateDidResponse) GetFullyQualifiedDidIdentifier() string {
	if m != nil {
		return m.FullyQualifiedDidIdentifier
	}
	return ""
}

type MsgUpdateDidRequest struct {
	Did Did `protobuf:"bytes,1,opt,name=did,proto3" json:"did"`
}

func (m *MsgUpdateDidRequest) Reset()         { *m = MsgUpdateDidRequest{} }
func (m *MsgUpdateDidRequest) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateDidRequest) ProtoMessage()    {}
func (*MsgUpdateDidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{2}
}
func (m *MsgUpdateDidRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateDidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateDidRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateDidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateDidRequest.Merge(m, src)
}
func (m *MsgUpdateDidRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateDidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateDidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateDidRequest proto.InternalMessageInfo

func (m *MsgUpdateDidRequest) GetDid() Did {
	if m != nil {
		return m.Did
	}
	return Did{}
}

type MsgUpdateDidResponse struct {
}

func (m *MsgUpdateDidResponse) Reset()         { *m = MsgUpdateDidResponse{} }
func (m *MsgUpdateDidResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateDidResponse) ProtoMessage()    {}
func (*MsgUpdateDidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{3}
}
func (m *MsgUpdateDidResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateDidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateDidResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateDidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateDidResponse.Merge(m, src)
}
func (m *MsgUpdateDidResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateDidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateDidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateDidResponse proto.InternalMessageInfo

type MsgDeleteDidRequest struct {
	Creator                     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	FullyQualifiedDidIdentifier string `protobuf:"bytes,2,opt,name=fullyQualifiedDidIdentifier,proto3" json:"fullyQualifiedDidIdentifier,omitempty"`
}

func (m *MsgDeleteDidRequest) Reset()         { *m = MsgDeleteDidRequest{} }
func (m *MsgDeleteDidRequest) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteDidRequest) ProtoMessage()    {}
func (*MsgDeleteDidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{4}
}
func (m *MsgDeleteDidRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteDidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteDidRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteDidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteDidRequest.Merge(m, src)
}
func (m *MsgDeleteDidRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteDidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteDidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteDidRequest proto.InternalMessageInfo

func (m *MsgDeleteDidRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteDidRequest) GetFullyQualifiedDidIdentifier() string {
	if m != nil {
		return m.FullyQualifiedDidIdentifier
	}
	return ""
}

type MsgDeleteDidResponse struct {
}

func (m *MsgDeleteDidResponse) Reset()         { *m = MsgDeleteDidResponse{} }
func (m *MsgDeleteDidResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteDidResponse) ProtoMessage()    {}
func (*MsgDeleteDidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{5}
}
func (m *MsgDeleteDidResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteDidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteDidResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteDidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteDidResponse.Merge(m, src)
}
func (m *MsgDeleteDidResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteDidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteDidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteDidResponse proto.InternalMessageInfo

type MsgCreateDidDocumentRequest struct {
	Creator     string      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	DidDocument DidDocument `protobuf:"bytes,2,opt,name=didDocument,proto3" json:"didDocument"`
}

func (m *MsgCreateDidDocumentRequest) Reset()         { *m = MsgCreateDidDocumentRequest{} }
func (m *MsgCreateDidDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDidDocumentRequest) ProtoMessage()    {}
func (*MsgCreateDidDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{6}
}
func (m *MsgCreateDidDocumentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateDidDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateDidDocumentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateDidDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDidDocumentRequest.Merge(m, src)
}
func (m *MsgCreateDidDocumentRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateDidDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDidDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDidDocumentRequest proto.InternalMessageInfo

func (m *MsgCreateDidDocumentRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateDidDocumentRequest) GetDidDocument() DidDocument {
	if m != nil {
		return m.DidDocument
	}
	return DidDocument{}
}

type MsgCreateDidDocumentResponse struct {
	FullyQualifiedDidIdentifier string `protobuf:"bytes,1,opt,name=fullyQualifiedDidIdentifier,proto3" json:"fullyQualifiedDidIdentifier,omitempty"`
}

func (m *MsgCreateDidDocumentResponse) Reset()         { *m = MsgCreateDidDocumentResponse{} }
func (m *MsgCreateDidDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDidDocumentResponse) ProtoMessage()    {}
func (*MsgCreateDidDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{7}
}
func (m *MsgCreateDidDocumentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateDidDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateDidDocumentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateDidDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDidDocumentResponse.Merge(m, src)
}
func (m *MsgCreateDidDocumentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateDidDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDidDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDidDocumentResponse proto.InternalMessageInfo

func (m *MsgCreateDidDocumentResponse) GetFullyQualifiedDidIdentifier() string {
	if m != nil {
		return m.FullyQualifiedDidIdentifier
	}
	return ""
}

type MsgUpdateDidDocumentRequest struct {
	Creator     string      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	DidDocument DidDocument `protobuf:"bytes,2,opt,name=didDocument,proto3" json:"didDocument"`
}

func (m *MsgUpdateDidDocumentRequest) Reset()         { *m = MsgUpdateDidDocumentRequest{} }
func (m *MsgUpdateDidDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateDidDocumentRequest) ProtoMessage()    {}
func (*MsgUpdateDidDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{8}
}
func (m *MsgUpdateDidDocumentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateDidDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateDidDocumentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateDidDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateDidDocumentRequest.Merge(m, src)
}
func (m *MsgUpdateDidDocumentRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateDidDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateDidDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateDidDocumentRequest proto.InternalMessageInfo

func (m *MsgUpdateDidDocumentRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateDidDocumentRequest) GetDidDocument() DidDocument {
	if m != nil {
		return m.DidDocument
	}
	return DidDocument{}
}

type MsgUpdateDidDocumentResponse struct {
}

func (m *MsgUpdateDidDocumentResponse) Reset()         { *m = MsgUpdateDidDocumentResponse{} }
func (m *MsgUpdateDidDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateDidDocumentResponse) ProtoMessage()    {}
func (*MsgUpdateDidDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{9}
}
func (m *MsgUpdateDidDocumentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateDidDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateDidDocumentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateDidDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateDidDocumentResponse.Merge(m, src)
}
func (m *MsgUpdateDidDocumentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateDidDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateDidDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateDidDocumentResponse proto.InternalMessageInfo

type MsgDeleteDidDocumentRequest struct {
	Creator                     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	FullyQualifiedDidIdentifier string `protobuf:"bytes,2,opt,name=fullyQualifiedDidIdentifier,proto3" json:"fullyQualifiedDidIdentifier,omitempty"`
}

func (m *MsgDeleteDidDocumentRequest) Reset()         { *m = MsgDeleteDidDocumentRequest{} }
func (m *MsgDeleteDidDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteDidDocumentRequest) ProtoMessage()    {}
func (*MsgDeleteDidDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{10}
}
func (m *MsgDeleteDidDocumentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteDidDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteDidDocumentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteDidDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteDidDocumentRequest.Merge(m, src)
}
func (m *MsgDeleteDidDocumentRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteDidDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteDidDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteDidDocumentRequest proto.InternalMessageInfo

func (m *MsgDeleteDidDocumentRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteDidDocumentRequest) GetFullyQualifiedDidIdentifier() string {
	if m != nil {
		return m.FullyQualifiedDidIdentifier
	}
	return ""
}

type MsgDeleteDidDocumentResponse struct {
}

func (m *MsgDeleteDidDocumentResponse) Reset()         { *m = MsgDeleteDidDocumentResponse{} }
func (m *MsgDeleteDidDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteDidDocumentResponse) ProtoMessage()    {}
func (*MsgDeleteDidDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75a0fe48247b413f, []int{11}
}
func (m *MsgDeleteDidDocumentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteDidDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteDidDocumentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteDidDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteDidDocumentResponse.Merge(m, src)
}
func (m *MsgDeleteDidDocumentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteDidDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteDidDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteDidDocumentResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateDidRequest)(nil), "beheroes.doxchain.did.MsgCreateDidRequest")
	proto.RegisterType((*MsgCreateDidResponse)(nil), "beheroes.doxchain.did.MsgCreateDidResponse")
	proto.RegisterType((*MsgUpdateDidRequest)(nil), "beheroes.doxchain.did.MsgUpdateDidRequest")
	proto.RegisterType((*MsgUpdateDidResponse)(nil), "beheroes.doxchain.did.MsgUpdateDidResponse")
	proto.RegisterType((*MsgDeleteDidRequest)(nil), "beheroes.doxchain.did.MsgDeleteDidRequest")
	proto.RegisterType((*MsgDeleteDidResponse)(nil), "beheroes.doxchain.did.MsgDeleteDidResponse")
	proto.RegisterType((*MsgCreateDidDocumentRequest)(nil), "beheroes.doxchain.did.MsgCreateDidDocumentRequest")
	proto.RegisterType((*MsgCreateDidDocumentResponse)(nil), "beheroes.doxchain.did.MsgCreateDidDocumentResponse")
	proto.RegisterType((*MsgUpdateDidDocumentRequest)(nil), "beheroes.doxchain.did.MsgUpdateDidDocumentRequest")
	proto.RegisterType((*MsgUpdateDidDocumentResponse)(nil), "beheroes.doxchain.did.MsgUpdateDidDocumentResponse")
	proto.RegisterType((*MsgDeleteDidDocumentRequest)(nil), "beheroes.doxchain.did.MsgDeleteDidDocumentRequest")
	proto.RegisterType((*MsgDeleteDidDocumentResponse)(nil), "beheroes.doxchain.did.MsgDeleteDidDocumentResponse")
}

func init() { proto.RegisterFile("doxchain/did/tx.proto", fileDescriptor_75a0fe48247b413f) }

var fileDescriptor_75a0fe48247b413f = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0x4b, 0x6a, 0xdb, 0x40,
	0x18, 0x80, 0xa5, 0xa6, 0x0f, 0x3c, 0x5e, 0x55, 0x4d, 0x42, 0x50, 0x8a, 0x52, 0xb4, 0xea, 0x83,
	0x4a, 0xa0, 0x5c, 0xa0, 0x24, 0xda, 0xa4, 0x90, 0x45, 0x0d, 0x85, 0xd2, 0x4d, 0x6b, 0xe9, 0x9f,
	0xc8, 0x03, 0x8a, 0x46, 0xd1, 0x03, 0x6c, 0xe8, 0xae, 0x17, 0xe8, 0x55, 0x7a, 0x0b, 0x2f, 0xbd,
	0xec, 0xaa, 0x14, 0xfb, 0x22, 0x45, 0x33, 0x23, 0x59, 0xd6, 0x63, 0xec, 0xe2, 0x42, 0x76, 0x96,
	0xfc, 0x6b, 0xbe, 0xef, 0x7f, 0x31, 0xe8, 0x08, 0xe8, 0xd4, 0x9f, 0x8c, 0x49, 0x64, 0x03, 0x01,
	0x3b, 0x9b, 0x5a, 0x71, 0x42, 0x33, 0xaa, 0x1d, 0x79, 0x78, 0x82, 0x13, 0x8a, 0x53, 0xab, 0xfc,
	0xdf, 0x02, 0x02, 0xfa, 0x61, 0x40, 0x03, 0xca, 0x22, 0xec, 0xe2, 0x17, 0x0f, 0xd6, 0x8f, 0x37,
	0xce, 0x00, 0x02, 0xe2, 0xfd, 0x59, 0xf3, 0xfd, 0x17, 0xa0, 0x7e, 0x7e, 0x8b, 0xa3, 0x8c, 0x07,
	0x98, 0x57, 0xe8, 0xd9, 0x75, 0x1a, 0x5c, 0x26, 0x78, 0x9c, 0x61, 0x97, 0xc0, 0x08, 0xdf, 0xe5,
	0x38, 0xcd, 0x34, 0x07, 0x1d, 0x00, 0x81, 0x13, 0xf5, 0x85, 0xfa, 0x72, 0xe8, 0xe8, 0x56, 0xa7,
	0x8a, 0xe5, 0x12, 0xb8, 0x78, 0x38, 0xff, 0x7d, 0xa6, 0x8c, 0x8a, 0x60, 0xf3, 0x13, 0x3a, 0xdc,
	0x3c, 0x2a, 0x8d, 0x69, 0x94, 0x62, 0xed, 0x1d, 0x3a, 0xbd, 0xc9, 0xc3, 0x70, 0xf6, 0x21, 0x1f,
	0x87, 0xe4, 0x86, 0x60, 0x70, 0x09, 0x5c, 0x01, 0x8e, 0xb2, 0xe2, 0x21, 0x61, 0x8c, 0xc1, 0x48,
	0x16, 0x22, 0x24, 0x3f, 0xc6, 0xb0, 0xbf, 0xe4, 0x31, 0x93, 0xac, 0x1d, 0xc5, 0x25, 0xcd, 0x3b,
	0x86, 0x70, 0x71, 0x88, 0x37, 0x10, 0x27, 0xe8, 0x89, 0x5f, 0x24, 0x44, 0x4b, 0xcf, 0xf2, 0x71,
	0x5b, 0x56, 0x0f, 0xb6, 0x67, 0xc5, 0x55, 0x6a, 0x48, 0xa1, 0xf2, 0x5d, 0x45, 0xa7, 0xf5, 0x42,
	0xba, 0xa2, 0x63, 0xdb, 0x9d, 0xde, 0xa3, 0x21, 0xac, 0xe3, 0x99, 0xc3, 0xd0, 0x31, 0xfb, 0x0b,
	0x53, 0x46, 0x8a, 0x02, 0xd5, 0x3f, 0x36, 0xbf, 0xa2, 0xe7, 0xdd, 0x12, 0xff, 0xad, 0xab, 0x22,
	0xcf, 0xaa, 0x17, 0xf7, 0x93, 0xa7, 0xc1, 0xf2, 0xec, 0x90, 0x10, 0xdd, 0x98, 0x31, 0xc9, 0xaa,
	0x4b, 0xbb, 0x4b, 0xee, 0x3f, 0x20, 0x5c, 0xad, 0x03, 0xcd, 0xd5, 0x9c, 0x9f, 0x8f, 0xd0, 0xc1,
	0x75, 0x1a, 0x68, 0x80, 0x06, 0x55, 0x9f, 0xb4, 0xd7, 0x3d, 0x65, 0xe8, 0xd8, 0x72, 0xfd, 0xcd,
	0x4e, 0xb1, 0xa2, 0xe1, 0x80, 0x06, 0x55, 0x95, 0x64, 0x94, 0xe6, 0x9a, 0xca, 0x28, 0xad, 0x3d,
	0x2c, 0x28, 0x55, 0xc2, 0x32, 0x4a, 0x73, 0x53, 0x65, 0x94, 0xd6, 0x8a, 0x69, 0xdf, 0xd0, 0xd3,
	0xd6, 0x64, 0x6b, 0xce, 0x0e, 0xd5, 0x68, 0xb4, 0x5f, 0x3f, 0xff, 0xa7, 0x6f, 0xd6, 0xf4, 0xd6,
	0xbc, 0xc9, 0xe8, 0x7d, 0x1b, 0x22, 0xa3, 0xf7, 0x0e, 0x74, 0x41, 0x6f, 0x8d, 0x94, 0x8c, 0xde,
	0x37, 0xfa, 0x32, 0x7a, 0xef, 0xcc, 0x5e, 0x5c, 0xce, 0x97, 0x86, 0xba, 0x58, 0x1a, 0xea, 0x9f,
	0xa5, 0xa1, 0xfe, 0x58, 0x19, 0xca, 0x62, 0x65, 0x28, 0xbf, 0x56, 0x86, 0xf2, 0xf9, 0x55, 0x40,
	0xb2, 0x49, 0xee, 0x59, 0x3e, 0xbd, 0xb5, 0x3d, 0xfc, 0x96, 0x9f, 0x6c, 0x57, 0xf7, 0xd7, 0x94,
	0xdf, 0x8e, 0xb3, 0x18, 0xa7, 0xde, 0x63, 0x76, 0x77, 0x9d, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x3d, 0x68, 0xdc, 0x4e, 0x3a, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateDid(ctx context.Context, in *MsgCreateDidRequest, opts ...grpc.CallOption) (*MsgCreateDidResponse, error)
	UpdateDid(ctx context.Context, in *MsgUpdateDidRequest, opts ...grpc.CallOption) (*MsgUpdateDidResponse, error)
	DeleteDid(ctx context.Context, in *MsgDeleteDidRequest, opts ...grpc.CallOption) (*MsgDeleteDidResponse, error)
	CreateDidDocument(ctx context.Context, in *MsgCreateDidDocumentRequest, opts ...grpc.CallOption) (*MsgCreateDidDocumentResponse, error)
	UpdateDidDocument(ctx context.Context, in *MsgUpdateDidDocumentRequest, opts ...grpc.CallOption) (*MsgUpdateDidDocumentResponse, error)
	DeleteDidDocument(ctx context.Context, in *MsgDeleteDidDocumentRequest, opts ...grpc.CallOption) (*MsgDeleteDidDocumentResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateDid(ctx context.Context, in *MsgCreateDidRequest, opts ...grpc.CallOption) (*MsgCreateDidResponse, error) {
	out := new(MsgCreateDidResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.did.Msg/CreateDid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateDid(ctx context.Context, in *MsgUpdateDidRequest, opts ...grpc.CallOption) (*MsgUpdateDidResponse, error) {
	out := new(MsgUpdateDidResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.did.Msg/UpdateDid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteDid(ctx context.Context, in *MsgDeleteDidRequest, opts ...grpc.CallOption) (*MsgDeleteDidResponse, error) {
	out := new(MsgDeleteDidResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.did.Msg/DeleteDid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateDidDocument(ctx context.Context, in *MsgCreateDidDocumentRequest, opts ...grpc.CallOption) (*MsgCreateDidDocumentResponse, error) {
	out := new(MsgCreateDidDocumentResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.did.Msg/CreateDidDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateDidDocument(ctx context.Context, in *MsgUpdateDidDocumentRequest, opts ...grpc.CallOption) (*MsgUpdateDidDocumentResponse, error) {
	out := new(MsgUpdateDidDocumentResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.did.Msg/UpdateDidDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteDidDocument(ctx context.Context, in *MsgDeleteDidDocumentRequest, opts ...grpc.CallOption) (*MsgDeleteDidDocumentResponse, error) {
	out := new(MsgDeleteDidDocumentResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.did.Msg/DeleteDidDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateDid(context.Context, *MsgCreateDidRequest) (*MsgCreateDidResponse, error)
	UpdateDid(context.Context, *MsgUpdateDidRequest) (*MsgUpdateDidResponse, error)
	DeleteDid(context.Context, *MsgDeleteDidRequest) (*MsgDeleteDidResponse, error)
	CreateDidDocument(context.Context, *MsgCreateDidDocumentRequest) (*MsgCreateDidDocumentResponse, error)
	UpdateDidDocument(context.Context, *MsgUpdateDidDocumentRequest) (*MsgUpdateDidDocumentResponse, error)
	DeleteDidDocument(context.Context, *MsgDeleteDidDocumentRequest) (*MsgDeleteDidDocumentResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateDid(ctx context.Context, req *MsgCreateDidRequest) (*MsgCreateDidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDid not implemented")
}
func (*UnimplementedMsgServer) UpdateDid(ctx context.Context, req *MsgUpdateDidRequest) (*MsgUpdateDidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDid not implemented")
}
func (*UnimplementedMsgServer) DeleteDid(ctx context.Context, req *MsgDeleteDidRequest) (*MsgDeleteDidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDid not implemented")
}
func (*UnimplementedMsgServer) CreateDidDocument(ctx context.Context, req *MsgCreateDidDocumentRequest) (*MsgCreateDidDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDidDocument not implemented")
}
func (*UnimplementedMsgServer) UpdateDidDocument(ctx context.Context, req *MsgUpdateDidDocumentRequest) (*MsgUpdateDidDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDidDocument not implemented")
}
func (*UnimplementedMsgServer) DeleteDidDocument(ctx context.Context, req *MsgDeleteDidDocumentRequest) (*MsgDeleteDidDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDidDocument not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.did.Msg/CreateDid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateDid(ctx, req.(*MsgCreateDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.did.Msg/UpdateDid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateDid(ctx, req.(*MsgUpdateDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.did.Msg/DeleteDid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteDid(ctx, req.(*MsgDeleteDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateDidDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateDidDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateDidDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.did.Msg/CreateDidDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateDidDocument(ctx, req.(*MsgCreateDidDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateDidDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateDidDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateDidDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.did.Msg/UpdateDidDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateDidDocument(ctx, req.(*MsgUpdateDidDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteDidDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteDidDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteDidDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.did.Msg/DeleteDidDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteDidDocument(ctx, req.(*MsgDeleteDidDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "beheroes.doxchain.did.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDid",
			Handler:    _Msg_CreateDid_Handler,
		},
		{
			MethodName: "UpdateDid",
			Handler:    _Msg_UpdateDid_Handler,
		},
		{
			MethodName: "DeleteDid",
			Handler:    _Msg_DeleteDid_Handler,
		},
		{
			MethodName: "CreateDidDocument",
			Handler:    _Msg_CreateDidDocument_Handler,
		},
		{
			MethodName: "UpdateDidDocument",
			Handler:    _Msg_UpdateDidDocument_Handler,
		},
		{
			MethodName: "DeleteDidDocument",
			Handler:    _Msg_DeleteDidDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doxchain/did/tx.proto",
}

func (m *MsgCreateDidRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateDidRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateDidRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Did.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgCreateDidResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateDidResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateDidResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FullyQualifiedDidIdentifier) > 0 {
		i -= len(m.FullyQualifiedDidIdentifier)
		copy(dAtA[i:], m.FullyQualifiedDidIdentifier)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FullyQualifiedDidIdentifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateDidRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateDidRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateDidRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Did.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgUpdateDidResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateDidResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateDidResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteDidRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteDidRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteDidRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FullyQualifiedDidIdentifier) > 0 {
		i -= len(m.FullyQualifiedDidIdentifier)
		copy(dAtA[i:], m.FullyQualifiedDidIdentifier)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FullyQualifiedDidIdentifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteDidResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteDidResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteDidResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateDidDocumentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateDidDocumentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateDidDocumentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DidDocument.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateDidDocumentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateDidDocumentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateDidDocumentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FullyQualifiedDidIdentifier) > 0 {
		i -= len(m.FullyQualifiedDidIdentifier)
		copy(dAtA[i:], m.FullyQualifiedDidIdentifier)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FullyQualifiedDidIdentifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateDidDocumentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateDidDocumentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateDidDocumentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DidDocument.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateDidDocumentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateDidDocumentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateDidDocumentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteDidDocumentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteDidDocumentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteDidDocumentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FullyQualifiedDidIdentifier) > 0 {
		i -= len(m.FullyQualifiedDidIdentifier)
		copy(dAtA[i:], m.FullyQualifiedDidIdentifier)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FullyQualifiedDidIdentifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteDidDocumentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteDidDocumentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteDidDocumentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateDidRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Did.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCreateDidResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FullyQualifiedDidIdentifier)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateDidRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Did.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateDidResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteDidRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FullyQualifiedDidIdentifier)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteDidResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateDidDocumentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.DidDocument.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCreateDidDocumentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FullyQualifiedDidIdentifier)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateDidDocumentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.DidDocument.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateDidDocumentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteDidDocumentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FullyQualifiedDidIdentifier)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteDidDocumentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateDidRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateDidRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateDidRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Did.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateDidResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateDidResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateDidResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FullyQualifiedDidIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FullyQualifiedDidIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateDidRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateDidRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateDidRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Did.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateDidResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateDidResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateDidResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteDidRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteDidRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteDidRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FullyQualifiedDidIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FullyQualifiedDidIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteDidResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteDidResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteDidResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateDidDocumentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateDidDocumentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateDidDocumentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidDocument", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DidDocument.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateDidDocumentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateDidDocumentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateDidDocumentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FullyQualifiedDidIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FullyQualifiedDidIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateDidDocumentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateDidDocumentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateDidDocumentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidDocument", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DidDocument.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateDidDocumentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateDidDocumentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateDidDocumentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteDidDocumentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteDidDocumentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteDidDocumentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FullyQualifiedDidIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FullyQualifiedDidIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteDidDocumentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteDidDocumentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteDidDocumentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
