// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: doxchain/abs/v1beta1/watchlist_entry.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type WatchlistEntry struct {
	Address     string                                   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
	BlockHeight uint64                                   `protobuf:"varint,2,opt,name=blockHeight,proto3" json:"blockHeight,omitempty" yaml:"blockheight"`
	Coins       github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=coins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"coins" yaml:"coins"`
}

func (m *WatchlistEntry) Reset()         { *m = WatchlistEntry{} }
func (m *WatchlistEntry) String() string { return proto.CompactTextString(m) }
func (*WatchlistEntry) ProtoMessage()    {}
func (*WatchlistEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_76e6b6f148d89538, []int{0}
}
func (m *WatchlistEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WatchlistEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WatchlistEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WatchlistEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchlistEntry.Merge(m, src)
}
func (m *WatchlistEntry) XXX_Size() int {
	return m.Size()
}
func (m *WatchlistEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchlistEntry.DiscardUnknown(m)
}

var xxx_messageInfo_WatchlistEntry proto.InternalMessageInfo

func (m *WatchlistEntry) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *WatchlistEntry) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *WatchlistEntry) GetCoins() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Coins
	}
	return nil
}

func init() {
	proto.RegisterType((*WatchlistEntry)(nil), "beheroes.doxchain.abs.v1beta1.WatchlistEntry")
}

func init() {
	proto.RegisterFile("doxchain/abs/v1beta1/watchlist_entry.proto", fileDescriptor_76e6b6f148d89538)
}

var fileDescriptor_76e6b6f148d89538 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0x3f, 0x4b, 0xf3, 0x40,
	0x18, 0xcf, 0xbd, 0x7d, 0x55, 0x4c, 0xa5, 0x43, 0x10, 0xa9, 0x05, 0x2f, 0x25, 0x53, 0x14, 0x7b,
	0x47, 0x75, 0x11, 0x27, 0x49, 0x11, 0x9c, 0xbb, 0x08, 0x2e, 0x72, 0x97, 0x1c, 0x49, 0x68, 0x9b,
	0xab, 0x79, 0x4e, 0x6d, 0xbf, 0x85, 0x9f, 0xc3, 0x4f, 0xd2, 0xb1, 0xa3, 0x53, 0x94, 0x76, 0x74,
	0xeb, 0x27, 0x90, 0xdc, 0x25, 0xa5, 0xd3, 0x1d, 0xfc, 0xfe, 0x3e, 0xcf, 0x63, 0x5f, 0x44, 0x72,
	0x16, 0x26, 0x2c, 0xcd, 0x28, 0xe3, 0x40, 0xdf, 0xfa, 0x5c, 0x28, 0xd6, 0xa7, 0xef, 0x4c, 0x85,
	0xc9, 0x38, 0x05, 0xf5, 0x2c, 0x32, 0x95, 0xcf, 0xc9, 0x34, 0x97, 0x4a, 0x3a, 0x67, 0x5c, 0x24,
	0x22, 0x97, 0x02, 0x48, 0x2d, 0x22, 0x8c, 0x03, 0xa9, 0x44, 0x9d, 0xe3, 0x58, 0xc6, 0x52, 0x33,
	0x69, 0xf9, 0x33, 0xa2, 0x0e, 0x0e, 0x25, 0x4c, 0x24, 0x50, 0xce, 0x40, 0x6c, 0xfd, 0x43, 0x99,
	0x66, 0x06, 0xf7, 0x7e, 0x91, 0xdd, 0x7a, 0xac, 0xe3, 0xee, 0xcb, 0x34, 0xe7, 0xd2, 0x3e, 0x60,
	0x51, 0x94, 0x0b, 0x80, 0x36, 0xea, 0x22, 0xff, 0x30, 0x70, 0x36, 0x85, 0xdb, 0x9a, 0xb3, 0xc9,
	0xf8, 0xd6, 0xab, 0x00, 0x6f, 0x58, 0x53, 0x9c, 0x1b, 0xbb, 0xc9, 0xc7, 0x32, 0x1c, 0x3d, 0x88,
	0x34, 0x4e, 0x54, 0xfb, 0x5f, 0x17, 0xf9, 0xff, 0x83, 0x93, 0x4d, 0xe1, 0x3a, 0x46, 0xa1, 0xc1,
	0x44, 0x83, 0xde, 0x70, 0x97, 0xea, 0xbc, 0xd8, 0x7b, 0x65, 0x11, 0x68, 0x37, 0xba, 0x0d, 0xbf,
	0x79, 0x75, 0x4a, 0x4c, 0x55, 0x52, 0x56, 0xad, 0xa7, 0x22, 0x03, 0x99, 0x66, 0xc1, 0xdd, 0xa2,
	0x70, 0xad, 0x4d, 0xe1, 0x1e, 0x19, 0x4b, 0xad, 0xf2, 0x3e, 0xbf, 0x5d, 0x3f, 0x4e, 0x55, 0xf2,
	0xca, 0x49, 0x28, 0x27, 0xb4, 0x9a, 0xd3, 0x3c, 0x3d, 0x88, 0x46, 0x54, 0xcd, 0xa7, 0x02, 0xb4,
	0x01, 0x0c, 0x4d, 0x52, 0x30, 0x58, 0xac, 0x30, 0x5a, 0xae, 0x30, 0xfa, 0x59, 0x61, 0xf4, 0xb1,
	0xc6, 0xd6, 0x72, 0x8d, 0xad, 0xaf, 0x35, 0xb6, 0x9e, 0xce, 0x77, 0xac, 0xb8, 0xe8, 0x99, 0x45,
	0xd3, 0xed, 0x75, 0x66, 0xfa, 0x3e, 0xda, 0x91, 0xef, 0xeb, 0xcd, 0x5d, 0xff, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x43, 0x4f, 0x2b, 0x93, 0xbc, 0x01, 0x00, 0x00,
}

func (m *WatchlistEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WatchlistEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WatchlistEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Coins) > 0 {
		for iNdEx := len(m.Coins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Coins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWatchlistEntry(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.BlockHeight != 0 {
		i = encodeVarintWatchlistEntry(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintWatchlistEntry(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintWatchlistEntry(dAtA []byte, offset int, v uint64) int {
	offset -= sovWatchlistEntry(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *WatchlistEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovWatchlistEntry(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovWatchlistEntry(uint64(m.BlockHeight))
	}
	if len(m.Coins) > 0 {
		for _, e := range m.Coins {
			l = e.Size()
			n += 1 + l + sovWatchlistEntry(uint64(l))
		}
	}
	return n
}

func sovWatchlistEntry(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWatchlistEntry(x uint64) (n int) {
	return sovWatchlistEntry(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *WatchlistEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWatchlistEntry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WatchlistEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WatchlistEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWatchlistEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWatchlistEntry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWatchlistEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWatchlistEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWatchlistEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWatchlistEntry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWatchlistEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = append(m.Coins, types.Coin{})
			if err := m.Coins[len(m.Coins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWatchlistEntry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWatchlistEntry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWatchlistEntry(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWatchlistEntry
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWatchlistEntry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWatchlistEntry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWatchlistEntry
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWatchlistEntry
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWatchlistEntry
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWatchlistEntry        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWatchlistEntry          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWatchlistEntry = fmt.Errorf("proto: unexpected end of group")
)
