// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: doxchain/idp/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99966fcdbdb4a7b, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99966fcdbdb4a7b, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetDotWellKnownRequest struct {
	TenantW3CIdentifier string `protobuf:"bytes,1,opt,name=tenantW3CIdentifier,proto3" json:"tenantW3CIdentifier,omitempty"`
}

func (m *QueryGetDotWellKnownRequest) Reset()         { *m = QueryGetDotWellKnownRequest{} }
func (m *QueryGetDotWellKnownRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDotWellKnownRequest) ProtoMessage()    {}
func (*QueryGetDotWellKnownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99966fcdbdb4a7b, []int{2}
}
func (m *QueryGetDotWellKnownRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDotWellKnownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDotWellKnownRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDotWellKnownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDotWellKnownRequest.Merge(m, src)
}
func (m *QueryGetDotWellKnownRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDotWellKnownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDotWellKnownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDotWellKnownRequest proto.InternalMessageInfo

func (m *QueryGetDotWellKnownRequest) GetTenantW3CIdentifier() string {
	if m != nil {
		return m.TenantW3CIdentifier
	}
	return ""
}

type QueryGetDotWellKnownResponse struct {
	Issuer                                 string   `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	AuthorizationEndpoint                  string   `protobuf:"bytes,2,opt,name=authorizationEndpoint,json=authorization_endpoint,proto3" json:"authorizationEndpoint,omitempty"`
	TokenEndpoint                          string   `protobuf:"bytes,3,opt,name=tokenEndpoint,json=token_endpoint,proto3" json:"tokenEndpoint,omitempty"`
	TokenEndpointAuthMethodsSupported      []string `protobuf:"bytes,4,rep,name=tokenEndpointAuthMethodsSupported,json=token_endpoint_auth_methods_supported,proto3" json:"tokenEndpointAuthMethodsSupported,omitempty"`
	TokenEndpointAuthSigningAlgosSupported []string `protobuf:"bytes,5,rep,name=tokenEndpointAuthSigningAlgosSupported,json=token_endpoint_auth_signing_alg_values_supported,proto3" json:"tokenEndpointAuthSigningAlgosSupported,omitempty"`
	UserInfoEndpoint                       string   `protobuf:"bytes,6,opt,name=userInfoEndpoint,json=userinfo_endpoint,proto3" json:"userInfoEndpoint,omitempty"`
	JwksUri                                string   `protobuf:"bytes,7,opt,name=jwksUri,json=jwks_uri,proto3" json:"jwksUri,omitempty"`
	RegistrationEndpoint                   string   `protobuf:"bytes,8,opt,name=registrationEndpoint,json=registration_endpoint,proto3" json:"registrationEndpoint,omitempty"`
	ScopesSupported                        string   `protobuf:"bytes,9,opt,name=scopesSupported,json=scopes_supported,proto3" json:"scopesSupported,omitempty"`
	ResponseTypesSupported                 string   `protobuf:"bytes,10,opt,name=responseTypesSupported,json=response_types_supported,proto3" json:"responseTypesSupported,omitempty"`
	ServiceDocumentation                   string   `protobuf:"bytes,11,opt,name=serviceDocumentation,json=service_documentation,proto3" json:"serviceDocumentation,omitempty"`
	UiLocalesSupported                     string   `protobuf:"bytes,12,opt,name=uiLocalesSupported,json=ui_locales_supported,proto3" json:"uiLocalesSupported,omitempty"`
}

func (m *QueryGetDotWellKnownResponse) Reset()         { *m = QueryGetDotWellKnownResponse{} }
func (m *QueryGetDotWellKnownResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDotWellKnownResponse) ProtoMessage()    {}
func (*QueryGetDotWellKnownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99966fcdbdb4a7b, []int{3}
}
func (m *QueryGetDotWellKnownResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDotWellKnownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDotWellKnownResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDotWellKnownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDotWellKnownResponse.Merge(m, src)
}
func (m *QueryGetDotWellKnownResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDotWellKnownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDotWellKnownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDotWellKnownResponse proto.InternalMessageInfo

func (m *QueryGetDotWellKnownResponse) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *QueryGetDotWellKnownResponse) GetAuthorizationEndpoint() string {
	if m != nil {
		return m.AuthorizationEndpoint
	}
	return ""
}

func (m *QueryGetDotWellKnownResponse) GetTokenEndpoint() string {
	if m != nil {
		return m.TokenEndpoint
	}
	return ""
}

func (m *QueryGetDotWellKnownResponse) GetTokenEndpointAuthMethodsSupported() []string {
	if m != nil {
		return m.TokenEndpointAuthMethodsSupported
	}
	return nil
}

func (m *QueryGetDotWellKnownResponse) GetTokenEndpointAuthSigningAlgosSupported() []string {
	if m != nil {
		return m.TokenEndpointAuthSigningAlgosSupported
	}
	return nil
}

func (m *QueryGetDotWellKnownResponse) GetUserInfoEndpoint() string {
	if m != nil {
		return m.UserInfoEndpoint
	}
	return ""
}

func (m *QueryGetDotWellKnownResponse) GetJwksUri() string {
	if m != nil {
		return m.JwksUri
	}
	return ""
}

func (m *QueryGetDotWellKnownResponse) GetRegistrationEndpoint() string {
	if m != nil {
		return m.RegistrationEndpoint
	}
	return ""
}

func (m *QueryGetDotWellKnownResponse) GetScopesSupported() string {
	if m != nil {
		return m.ScopesSupported
	}
	return ""
}

func (m *QueryGetDotWellKnownResponse) GetResponseTypesSupported() string {
	if m != nil {
		return m.ResponseTypesSupported
	}
	return ""
}

func (m *QueryGetDotWellKnownResponse) GetServiceDocumentation() string {
	if m != nil {
		return m.ServiceDocumentation
	}
	return ""
}

func (m *QueryGetDotWellKnownResponse) GetUiLocalesSupported() string {
	if m != nil {
		return m.UiLocalesSupported
	}
	return ""
}

type QueryGetClientRegistrationRegistryRequest struct {
	ClientRegistrationRegistryW3CIdentifier string `protobuf:"bytes,1,opt,name=clientRegistrationRegistryW3CIdentifier,proto3" json:"clientRegistrationRegistryW3CIdentifier,omitempty"`
}

func (m *QueryGetClientRegistrationRegistryRequest) Reset() {
	*m = QueryGetClientRegistrationRegistryRequest{}
}
func (m *QueryGetClientRegistrationRegistryRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryGetClientRegistrationRegistryRequest) ProtoMessage() {}
func (*QueryGetClientRegistrationRegistryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99966fcdbdb4a7b, []int{4}
}
func (m *QueryGetClientRegistrationRegistryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetClientRegistrationRegistryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetClientRegistrationRegistryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetClientRegistrationRegistryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetClientRegistrationRegistryRequest.Merge(m, src)
}
func (m *QueryGetClientRegistrationRegistryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetClientRegistrationRegistryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetClientRegistrationRegistryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetClientRegistrationRegistryRequest proto.InternalMessageInfo

func (m *QueryGetClientRegistrationRegistryRequest) GetClientRegistrationRegistryW3CIdentifier() string {
	if m != nil {
		return m.ClientRegistrationRegistryW3CIdentifier
	}
	return ""
}

type QueryGetClientRegistrationRegistryResponse struct {
	ClientRegistrationRegistry ClientRegistrationRegistry `protobuf:"bytes,1,opt,name=clientRegistrationRegistry,proto3" json:"clientRegistrationRegistry"`
}

func (m *QueryGetClientRegistrationRegistryResponse) Reset() {
	*m = QueryGetClientRegistrationRegistryResponse{}
}
func (m *QueryGetClientRegistrationRegistryResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryGetClientRegistrationRegistryResponse) ProtoMessage() {}
func (*QueryGetClientRegistrationRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99966fcdbdb4a7b, []int{5}
}
func (m *QueryGetClientRegistrationRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetClientRegistrationRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetClientRegistrationRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetClientRegistrationRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetClientRegistrationRegistryResponse.Merge(m, src)
}
func (m *QueryGetClientRegistrationRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetClientRegistrationRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetClientRegistrationRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetClientRegistrationRegistryResponse proto.InternalMessageInfo

func (m *QueryGetClientRegistrationRegistryResponse) GetClientRegistrationRegistry() ClientRegistrationRegistry {
	if m != nil {
		return m.ClientRegistrationRegistry
	}
	return ClientRegistrationRegistry{}
}

type QueryAllClientRegistrationRegistryRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllClientRegistrationRegistryRequest) Reset() {
	*m = QueryAllClientRegistrationRegistryRequest{}
}
func (m *QueryAllClientRegistrationRegistryRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryAllClientRegistrationRegistryRequest) ProtoMessage() {}
func (*QueryAllClientRegistrationRegistryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99966fcdbdb4a7b, []int{6}
}
func (m *QueryAllClientRegistrationRegistryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllClientRegistrationRegistryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllClientRegistrationRegistryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllClientRegistrationRegistryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllClientRegistrationRegistryRequest.Merge(m, src)
}
func (m *QueryAllClientRegistrationRegistryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllClientRegistrationRegistryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllClientRegistrationRegistryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllClientRegistrationRegistryRequest proto.InternalMessageInfo

func (m *QueryAllClientRegistrationRegistryRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllClientRegistrationRegistryResponse struct {
	ClientRegistrationRegistry []ClientRegistrationRegistry `protobuf:"bytes,1,rep,name=clientRegistrationRegistry,proto3" json:"clientRegistrationRegistry"`
	Pagination                 *query.PageResponse          `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllClientRegistrationRegistryResponse) Reset() {
	*m = QueryAllClientRegistrationRegistryResponse{}
}
func (m *QueryAllClientRegistrationRegistryResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryAllClientRegistrationRegistryResponse) ProtoMessage() {}
func (*QueryAllClientRegistrationRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99966fcdbdb4a7b, []int{7}
}
func (m *QueryAllClientRegistrationRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllClientRegistrationRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllClientRegistrationRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllClientRegistrationRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllClientRegistrationRegistryResponse.Merge(m, src)
}
func (m *QueryAllClientRegistrationRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllClientRegistrationRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllClientRegistrationRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllClientRegistrationRegistryResponse proto.InternalMessageInfo

func (m *QueryAllClientRegistrationRegistryResponse) GetClientRegistrationRegistry() []ClientRegistrationRegistry {
	if m != nil {
		return m.ClientRegistrationRegistry
	}
	return nil
}

func (m *QueryAllClientRegistrationRegistryResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "beheroes.doxchain.idp.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "beheroes.doxchain.idp.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QueryGetDotWellKnownRequest)(nil), "beheroes.doxchain.idp.v1beta1.QueryGetDotWellKnownRequest")
	proto.RegisterType((*QueryGetDotWellKnownResponse)(nil), "beheroes.doxchain.idp.v1beta1.QueryGetDotWellKnownResponse")
	proto.RegisterType((*QueryGetClientRegistrationRegistryRequest)(nil), "beheroes.doxchain.idp.v1beta1.QueryGetClientRegistrationRegistryRequest")
	proto.RegisterType((*QueryGetClientRegistrationRegistryResponse)(nil), "beheroes.doxchain.idp.v1beta1.QueryGetClientRegistrationRegistryResponse")
	proto.RegisterType((*QueryAllClientRegistrationRegistryRequest)(nil), "beheroes.doxchain.idp.v1beta1.QueryAllClientRegistrationRegistryRequest")
	proto.RegisterType((*QueryAllClientRegistrationRegistryResponse)(nil), "beheroes.doxchain.idp.v1beta1.QueryAllClientRegistrationRegistryResponse")
}

func init() { proto.RegisterFile("doxchain/idp/v1beta1/query.proto", fileDescriptor_d99966fcdbdb4a7b) }

var fileDescriptor_d99966fcdbdb4a7b = []byte{
	// 904 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0x8e, 0xd3, 0x6d, 0x76, 0x3b, 0x0b, 0xec, 0x32, 0x9b, 0xad, 0x42, 0xd8, 0x0d, 0x59, 0x4b,
	0x6d, 0x37, 0x8b, 0xd6, 0x6e, 0x1b, 0x21, 0x58, 0xf6, 0x94, 0xcd, 0xc2, 0x52, 0x01, 0xa2, 0x4d,
	0x41, 0x85, 0x5e, 0x8c, 0x63, 0x4f, 0x9d, 0xa1, 0xce, 0x8c, 0xeb, 0x19, 0xb7, 0x0d, 0x55, 0x85,
	0x84, 0xc4, 0x8d, 0x03, 0x88, 0x03, 0xbf, 0x82, 0xff, 0xd1, 0x0b, 0x52, 0x25, 0x2e, 0x9c, 0x10,
	0x6a, 0x41, 0xe2, 0x17, 0x70, 0x46, 0x99, 0x19, 0x27, 0x36, 0x75, 0x1a, 0x83, 0xe0, 0x66, 0xcf,
	0xfb, 0xde, 0xf7, 0xbe, 0xef, 0x79, 0xe6, 0x8d, 0x41, 0xdd, 0xa5, 0x87, 0x4e, 0xcf, 0xc6, 0xc4,
	0xc4, 0x6e, 0x60, 0xee, 0xaf, 0x74, 0x11, 0xb7, 0x57, 0xcc, 0xbd, 0x08, 0x85, 0x03, 0x23, 0x08,
	0x29, 0xa7, 0xf0, 0x6e, 0x17, 0xf5, 0x50, 0x48, 0x11, 0x33, 0x62, 0xa8, 0x81, 0xdd, 0xc0, 0x50,
	0xd0, 0x6a, 0xd9, 0xa3, 0x1e, 0x15, 0x48, 0x73, 0xf8, 0x24, 0x93, 0xaa, 0x77, 0x3c, 0x4a, 0x3d,
	0x1f, 0x99, 0x76, 0x80, 0x4d, 0x9b, 0x10, 0xca, 0x6d, 0x8e, 0x29, 0x61, 0x2a, 0xfa, 0xc0, 0xa1,
	0xac, 0x4f, 0x99, 0xd9, 0xb5, 0x19, 0x92, 0xb5, 0x46, 0x95, 0x03, 0xdb, 0xc3, 0x44, 0x80, 0x15,
	0xf6, 0x5e, 0xa6, 0xc0, 0xc0, 0x0e, 0xed, 0x7e, 0x4c, 0xf7, 0x7a, 0x26, 0xc4, 0xf1, 0x31, 0x22,
	0xdc, 0x0a, 0x91, 0x87, 0x19, 0x0f, 0x05, 0x65, 0xfc, 0xa2, 0xac, 0xe9, 0x65, 0x00, 0x37, 0x86,
	0xd5, 0xd7, 0x05, 0x5b, 0x07, 0xed, 0x45, 0x88, 0x71, 0x7d, 0x1b, 0xdc, 0x4a, 0xad, 0xb2, 0x80,
	0x12, 0x86, 0x60, 0x1b, 0x94, 0x64, 0xd5, 0x8a, 0x56, 0xd7, 0xee, 0x5f, 0x5f, 0x5d, 0x30, 0x2e,
	0x6d, 0x8c, 0x21, 0xd3, 0x9f, 0x5c, 0x39, 0xf9, 0xe5, 0x95, 0x42, 0x47, 0xa5, 0xea, 0x1f, 0x80,
	0x97, 0x05, 0xf7, 0x33, 0xc4, 0x9f, 0x52, 0xbe, 0x85, 0x7c, 0xff, 0x5d, 0x42, 0x0f, 0x88, 0x2a,
	0x0d, 0x97, 0xc1, 0x2d, 0x8e, 0x88, 0x4d, 0xf8, 0x56, 0xb3, 0xbd, 0xe6, 0x22, 0xc2, 0xf1, 0x0e,
	0x46, 0xa1, 0x28, 0x38, 0xd7, 0xc9, 0x0a, 0xe9, 0xdf, 0xce, 0x82, 0x3b, 0xd9, 0x8c, 0x4a, 0xf6,
	0x3c, 0x28, 0x61, 0xc6, 0xa2, 0x11, 0x8b, 0x7a, 0x83, 0xaf, 0x81, 0xdb, 0x76, 0xc4, 0x7b, 0x34,
	0xc4, 0x9f, 0x8b, 0xde, 0xbc, 0x45, 0xdc, 0x80, 0x62, 0xc2, 0x2b, 0x45, 0x01, 0x9b, 0x4f, 0x05,
	0x2d, 0xa4, 0xa2, 0x70, 0x01, 0x3c, 0xcf, 0xe9, 0x2e, 0x1a, 0xc3, 0x67, 0x04, 0xfc, 0x05, 0xb1,
	0x38, 0x86, 0xad, 0x83, 0x7b, 0x29, 0x58, 0x2b, 0xe2, 0xbd, 0xf7, 0x11, 0xef, 0x51, 0x97, 0x6d,
	0x46, 0x41, 0x40, 0x43, 0x8e, 0xdc, 0xca, 0x95, 0xfa, 0xcc, 0xfd, 0xb9, 0xce, 0x42, 0x3a, 0xd5,
	0x1a, 0x16, 0xb6, 0xfa, 0x12, 0x6b, 0xb1, 0x18, 0x0c, 0x3f, 0x05, 0x8b, 0x17, 0x18, 0x37, 0xb1,
	0x47, 0x30, 0xf1, 0x5a, 0xbe, 0x47, 0x13, 0xb4, 0xb3, 0x82, 0x76, 0x39, 0x8b, 0x96, 0xc9, 0x04,
	0xcb, 0xf6, 0x3d, 0x6b, 0xdf, 0xf6, 0x23, 0x94, 0xac, 0xf0, 0x2a, 0xb8, 0x19, 0x31, 0x14, 0xae,
	0x91, 0x1d, 0x3a, 0x72, 0x57, 0x12, 0xee, 0x5e, 0x1c, 0xae, 0x63, 0xb2, 0x43, 0xc7, 0x06, 0x5f,
	0x02, 0x57, 0x3f, 0x3b, 0xd8, 0x65, 0x1f, 0x85, 0xb8, 0x72, 0x55, 0x60, 0xae, 0x0d, 0x5f, 0xad,
	0x28, 0xc4, 0xb0, 0x09, 0xca, 0xc9, 0x4d, 0x37, 0xe2, 0xba, 0x26, 0x70, 0xb7, 0x53, 0x1b, 0x72,
	0xc4, 0xd7, 0x00, 0x37, 0x98, 0x43, 0x03, 0x94, 0xf0, 0x31, 0x27, 0xf0, 0x37, 0xe5, 0x72, 0x42,
	0xe7, 0x1b, 0x60, 0x3e, 0x54, 0x5f, 0xf7, 0xc3, 0x41, 0x2a, 0x03, 0x88, 0x8c, 0x4a, 0x1c, 0xb5,
	0xf8, 0x20, 0x9d, 0xd9, 0x04, 0x65, 0x86, 0xc2, 0x7d, 0xec, 0xa0, 0xa7, 0xd4, 0x89, 0xfa, 0x88,
	0xc8, 0x63, 0x59, 0xb9, 0x2e, 0x95, 0xa9, 0x98, 0xe5, 0x26, 0x83, 0x70, 0x19, 0xc0, 0x08, 0xbf,
	0x47, 0x1d, 0xdb, 0x4f, 0x96, 0x7a, 0x4e, 0xa4, 0x94, 0x23, 0x6c, 0xf9, 0x32, 0x34, 0x2e, 0xa3,
	0x7f, 0xa5, 0x81, 0x46, 0xbc, 0x27, 0xdb, 0xe2, 0x14, 0x76, 0x12, 0x9e, 0xd5, 0xf3, 0x20, 0xde,
	0xf3, 0x1f, 0x83, 0x25, 0x67, 0x22, 0x28, 0xeb, 0x1c, 0xe4, 0x85, 0xeb, 0x3f, 0x68, 0xe0, 0x41,
	0x1e, 0x1d, 0xea, 0xa4, 0x7c, 0x01, 0xaa, 0x93, 0x99, 0xd5, 0xa1, 0x7f, 0x34, 0xe5, 0xd0, 0x4f,
	0x2e, 0xa3, 0x06, 0xc1, 0x25, 0x25, 0x74, 0xa6, 0xda, 0xd6, 0xf2, 0xfd, 0xe9, 0x6d, 0x7b, 0x1b,
	0x80, 0xf1, 0xac, 0x54, 0xea, 0x16, 0x0d, 0x39, 0x58, 0x8d, 0xe1, 0x60, 0x35, 0xe4, 0x10, 0x1f,
	0x8f, 0x23, 0x0f, 0xa9, 0xdc, 0x4e, 0x22, 0x53, 0xff, 0x33, 0x6e, 0xd2, 0x94, 0xaa, 0x39, 0x9b,
	0x34, 0xf3, 0x3f, 0x37, 0x09, 0x3e, 0x4b, 0xf9, 0x2e, 0x0a, 0xdf, 0x4b, 0x53, 0x7d, 0x4b, 0xf5,
	0x49, 0xe3, 0xab, 0x7f, 0x94, 0xc0, 0xac, 0x30, 0x0e, 0xbf, 0xd7, 0x40, 0x49, 0x4e, 0x6b, 0xb8,
	0x32, 0x45, 0xfa, 0xc5, 0xeb, 0xa2, 0xba, 0xfa, 0x4f, 0x52, 0xa4, 0x0e, 0x7d, 0xf1, 0xcb, 0x9f,
	0x7e, 0xfb, 0xae, 0x58, 0x87, 0x35, 0xb3, 0x8b, 0x1e, 0xca, 0x64, 0x33, 0x75, 0x89, 0xc9, 0xeb,
	0x02, 0xfe, 0xa8, 0x81, 0x1b, 0x7f, 0x1b, 0xec, 0xf0, 0xcd, 0x3c, 0xf5, 0xb2, 0xef, 0x97, 0xea,
	0xe3, 0x7f, 0x95, 0xab, 0x44, 0xb7, 0x84, 0xe8, 0xc7, 0xf0, 0xd1, 0x24, 0xd1, 0x47, 0x19, 0x17,
	0xd4, 0xb1, 0x69, 0x1c, 0x20, 0xdf, 0x7f, 0xb8, 0x2b, 0xb4, 0x7f, 0x5d, 0x04, 0xd5, 0xc9, 0x5f,
	0x1f, 0xbe, 0x93, 0x53, 0xde, 0xd4, 0xd3, 0x51, 0x5d, 0xfb, 0x0f, 0x98, 0x94, 0xed, 0x4f, 0x84,
	0xed, 0x4d, 0xb8, 0x31, 0xc9, 0x76, 0xfa, 0x47, 0x63, 0x60, 0x1e, 0xe5, 0x9c, 0x4f, 0xc7, 0xf0,
	0x77, 0x0d, 0xdc, 0x9d, 0xac, 0xa0, 0xe5, 0xfb, 0xf9, 0x3a, 0x92, 0x67, 0x5e, 0xe4, 0xeb, 0x48,
	0xae, 0x19, 0xa0, 0x9b, 0xa2, 0x23, 0x0d, 0xb8, 0x94, 0xb3, 0x23, 0x4f, 0xda, 0x27, 0x67, 0x35,
	0xed, 0xf4, 0xac, 0xa6, 0xfd, 0x7a, 0x56, 0xd3, 0xbe, 0x39, 0xaf, 0x15, 0x4e, 0xcf, 0x6b, 0x85,
	0x9f, 0xcf, 0x6b, 0x85, 0xed, 0x86, 0x87, 0x79, 0x2f, 0xea, 0x1a, 0x0e, 0xed, 0x67, 0x91, 0x1d,
	0x0a, 0x3a, 0x71, 0x8d, 0x75, 0x4b, 0xe2, 0x9f, 0xad, 0xf9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb9, 0xd4, 0x9e, 0xe1, 0xb2, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	GetDotWellKnown(ctx context.Context, in *QueryGetDotWellKnownRequest, opts ...grpc.CallOption) (*QueryGetDotWellKnownResponse, error)
	ClientRegistrationRegistry(ctx context.Context, in *QueryGetClientRegistrationRegistryRequest, opts ...grpc.CallOption) (*QueryGetClientRegistrationRegistryResponse, error)
	ClientRegistrationRegistryAll(ctx context.Context, in *QueryAllClientRegistrationRegistryRequest, opts ...grpc.CallOption) (*QueryAllClientRegistrationRegistryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.idp.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDotWellKnown(ctx context.Context, in *QueryGetDotWellKnownRequest, opts ...grpc.CallOption) (*QueryGetDotWellKnownResponse, error) {
	out := new(QueryGetDotWellKnownResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.idp.v1beta1.Query/GetDotWellKnown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ClientRegistrationRegistry(ctx context.Context, in *QueryGetClientRegistrationRegistryRequest, opts ...grpc.CallOption) (*QueryGetClientRegistrationRegistryResponse, error) {
	out := new(QueryGetClientRegistrationRegistryResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.idp.v1beta1.Query/ClientRegistrationRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ClientRegistrationRegistryAll(ctx context.Context, in *QueryAllClientRegistrationRegistryRequest, opts ...grpc.CallOption) (*QueryAllClientRegistrationRegistryResponse, error) {
	out := new(QueryAllClientRegistrationRegistryResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.idp.v1beta1.Query/ClientRegistrationRegistryAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	GetDotWellKnown(context.Context, *QueryGetDotWellKnownRequest) (*QueryGetDotWellKnownResponse, error)
	ClientRegistrationRegistry(context.Context, *QueryGetClientRegistrationRegistryRequest) (*QueryGetClientRegistrationRegistryResponse, error)
	ClientRegistrationRegistryAll(context.Context, *QueryAllClientRegistrationRegistryRequest) (*QueryAllClientRegistrationRegistryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetDotWellKnown(ctx context.Context, req *QueryGetDotWellKnownRequest) (*QueryGetDotWellKnownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDotWellKnown not implemented")
}
func (*UnimplementedQueryServer) ClientRegistrationRegistry(ctx context.Context, req *QueryGetClientRegistrationRegistryRequest) (*QueryGetClientRegistrationRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientRegistrationRegistry not implemented")
}
func (*UnimplementedQueryServer) ClientRegistrationRegistryAll(ctx context.Context, req *QueryAllClientRegistrationRegistryRequest) (*QueryAllClientRegistrationRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientRegistrationRegistryAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.idp.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDotWellKnown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDotWellKnownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDotWellKnown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.idp.v1beta1.Query/GetDotWellKnown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDotWellKnown(ctx, req.(*QueryGetDotWellKnownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ClientRegistrationRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetClientRegistrationRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClientRegistrationRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.idp.v1beta1.Query/ClientRegistrationRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClientRegistrationRegistry(ctx, req.(*QueryGetClientRegistrationRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ClientRegistrationRegistryAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllClientRegistrationRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClientRegistrationRegistryAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.idp.v1beta1.Query/ClientRegistrationRegistryAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClientRegistrationRegistryAll(ctx, req.(*QueryAllClientRegistrationRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "beheroes.doxchain.idp.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetDotWellKnown",
			Handler:    _Query_GetDotWellKnown_Handler,
		},
		{
			MethodName: "ClientRegistrationRegistry",
			Handler:    _Query_ClientRegistrationRegistry_Handler,
		},
		{
			MethodName: "ClientRegistrationRegistryAll",
			Handler:    _Query_ClientRegistrationRegistryAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doxchain/idp/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetDotWellKnownRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDotWellKnownRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDotWellKnownRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TenantW3CIdentifier) > 0 {
		i -= len(m.TenantW3CIdentifier)
		copy(dAtA[i:], m.TenantW3CIdentifier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TenantW3CIdentifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDotWellKnownResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDotWellKnownResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDotWellKnownResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UiLocalesSupported) > 0 {
		i -= len(m.UiLocalesSupported)
		copy(dAtA[i:], m.UiLocalesSupported)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UiLocalesSupported)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.ServiceDocumentation) > 0 {
		i -= len(m.ServiceDocumentation)
		copy(dAtA[i:], m.ServiceDocumentation)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ServiceDocumentation)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.ResponseTypesSupported) > 0 {
		i -= len(m.ResponseTypesSupported)
		copy(dAtA[i:], m.ResponseTypesSupported)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ResponseTypesSupported)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.ScopesSupported) > 0 {
		i -= len(m.ScopesSupported)
		copy(dAtA[i:], m.ScopesSupported)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ScopesSupported)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.RegistrationEndpoint) > 0 {
		i -= len(m.RegistrationEndpoint)
		copy(dAtA[i:], m.RegistrationEndpoint)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RegistrationEndpoint)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.JwksUri) > 0 {
		i -= len(m.JwksUri)
		copy(dAtA[i:], m.JwksUri)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.JwksUri)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.UserInfoEndpoint) > 0 {
		i -= len(m.UserInfoEndpoint)
		copy(dAtA[i:], m.UserInfoEndpoint)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UserInfoEndpoint)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.TokenEndpointAuthSigningAlgosSupported) > 0 {
		for iNdEx := len(m.TokenEndpointAuthSigningAlgosSupported) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TokenEndpointAuthSigningAlgosSupported[iNdEx])
			copy(dAtA[i:], m.TokenEndpointAuthSigningAlgosSupported[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.TokenEndpointAuthSigningAlgosSupported[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.TokenEndpointAuthMethodsSupported) > 0 {
		for iNdEx := len(m.TokenEndpointAuthMethodsSupported) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TokenEndpointAuthMethodsSupported[iNdEx])
			copy(dAtA[i:], m.TokenEndpointAuthMethodsSupported[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.TokenEndpointAuthMethodsSupported[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.TokenEndpoint) > 0 {
		i -= len(m.TokenEndpoint)
		copy(dAtA[i:], m.TokenEndpoint)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TokenEndpoint)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AuthorizationEndpoint) > 0 {
		i -= len(m.AuthorizationEndpoint)
		copy(dAtA[i:], m.AuthorizationEndpoint)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AuthorizationEndpoint)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Issuer) > 0 {
		i -= len(m.Issuer)
		copy(dAtA[i:], m.Issuer)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Issuer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetClientRegistrationRegistryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetClientRegistrationRegistryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetClientRegistrationRegistryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ClientRegistrationRegistryW3CIdentifier) > 0 {
		i -= len(m.ClientRegistrationRegistryW3CIdentifier)
		copy(dAtA[i:], m.ClientRegistrationRegistryW3CIdentifier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ClientRegistrationRegistryW3CIdentifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetClientRegistrationRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetClientRegistrationRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetClientRegistrationRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ClientRegistrationRegistry.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllClientRegistrationRegistryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllClientRegistrationRegistryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllClientRegistrationRegistryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllClientRegistrationRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllClientRegistrationRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllClientRegistrationRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClientRegistrationRegistry) > 0 {
		for iNdEx := len(m.ClientRegistrationRegistry) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClientRegistrationRegistry[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetDotWellKnownRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TenantW3CIdentifier)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDotWellKnownResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.AuthorizationEndpoint)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.TokenEndpoint)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.TokenEndpointAuthMethodsSupported) > 0 {
		for _, s := range m.TokenEndpointAuthMethodsSupported {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.TokenEndpointAuthSigningAlgosSupported) > 0 {
		for _, s := range m.TokenEndpointAuthSigningAlgosSupported {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	l = len(m.UserInfoEndpoint)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.JwksUri)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RegistrationEndpoint)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ScopesSupported)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ResponseTypesSupported)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ServiceDocumentation)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.UiLocalesSupported)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetClientRegistrationRegistryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientRegistrationRegistryW3CIdentifier)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetClientRegistrationRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ClientRegistrationRegistry.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllClientRegistrationRegistryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllClientRegistrationRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ClientRegistrationRegistry) > 0 {
		for _, e := range m.ClientRegistrationRegistry {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDotWellKnownRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDotWellKnownRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDotWellKnownRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantW3CIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TenantW3CIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDotWellKnownResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDotWellKnownResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDotWellKnownResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizationEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizationEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenEndpointAuthMethodsSupported", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenEndpointAuthMethodsSupported = append(m.TokenEndpointAuthMethodsSupported, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenEndpointAuthSigningAlgosSupported", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenEndpointAuthSigningAlgosSupported = append(m.TokenEndpointAuthSigningAlgosSupported, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserInfoEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserInfoEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JwksUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JwksUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationEndpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistrationEndpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScopesSupported", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScopesSupported = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseTypesSupported", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResponseTypesSupported = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceDocumentation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceDocumentation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UiLocalesSupported", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UiLocalesSupported = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetClientRegistrationRegistryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetClientRegistrationRegistryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetClientRegistrationRegistryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientRegistrationRegistryW3CIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientRegistrationRegistryW3CIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetClientRegistrationRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetClientRegistrationRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetClientRegistrationRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientRegistrationRegistry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClientRegistrationRegistry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllClientRegistrationRegistryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllClientRegistrationRegistryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllClientRegistrationRegistryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllClientRegistrationRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllClientRegistrationRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllClientRegistrationRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientRegistrationRegistry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientRegistrationRegistry = append(m.ClientRegistrationRegistry, ClientRegistrationRegistry{})
			if err := m.ClientRegistrationRegistry[len(m.ClientRegistrationRegistry)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
