// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: doxchain/idp/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgAuthenticationRequest struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Tenant  string `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
}

func (m *MsgAuthenticationRequest) Reset()         { *m = MsgAuthenticationRequest{} }
func (m *MsgAuthenticationRequest) String() string { return proto.CompactTextString(m) }
func (*MsgAuthenticationRequest) ProtoMessage()    {}
func (*MsgAuthenticationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d303193384f0350d, []int{0}
}
func (m *MsgAuthenticationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAuthenticationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAuthenticationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAuthenticationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuthenticationRequest.Merge(m, src)
}
func (m *MsgAuthenticationRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgAuthenticationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuthenticationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuthenticationRequest proto.InternalMessageInfo

func (m *MsgAuthenticationRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAuthenticationRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type MsgAuthenticationResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (m *MsgAuthenticationResponse) Reset()         { *m = MsgAuthenticationResponse{} }
func (m *MsgAuthenticationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAuthenticationResponse) ProtoMessage()    {}
func (*MsgAuthenticationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d303193384f0350d, []int{1}
}
func (m *MsgAuthenticationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAuthenticationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAuthenticationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAuthenticationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuthenticationResponse.Merge(m, src)
}
func (m *MsgAuthenticationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAuthenticationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuthenticationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuthenticationResponse proto.InternalMessageInfo

func (m *MsgAuthenticationResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type MsgCreateClientRegistry struct {
	ClientRegistry *ClientRegistry `protobuf:"bytes,1,opt,name=clientRegistry,proto3" json:"clientRegistry,omitempty"`
}

func (m *MsgCreateClientRegistry) Reset()         { *m = MsgCreateClientRegistry{} }
func (m *MsgCreateClientRegistry) String() string { return proto.CompactTextString(m) }
func (*MsgCreateClientRegistry) ProtoMessage()    {}
func (*MsgCreateClientRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d303193384f0350d, []int{2}
}
func (m *MsgCreateClientRegistry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateClientRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateClientRegistry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateClientRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateClientRegistry.Merge(m, src)
}
func (m *MsgCreateClientRegistry) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateClientRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateClientRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateClientRegistry proto.InternalMessageInfo

func (m *MsgCreateClientRegistry) GetClientRegistry() *ClientRegistry {
	if m != nil {
		return m.ClientRegistry
	}
	return nil
}

type MsgCreateClientRegistryResponse struct {
}

func (m *MsgCreateClientRegistryResponse) Reset()         { *m = MsgCreateClientRegistryResponse{} }
func (m *MsgCreateClientRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateClientRegistryResponse) ProtoMessage()    {}
func (*MsgCreateClientRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d303193384f0350d, []int{3}
}
func (m *MsgCreateClientRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateClientRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateClientRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateClientRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateClientRegistryResponse.Merge(m, src)
}
func (m *MsgCreateClientRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateClientRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateClientRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateClientRegistryResponse proto.InternalMessageInfo

type MsgUpdateClientRegistry struct {
	ClientRegistry *ClientRegistry `protobuf:"bytes,1,opt,name=clientRegistry,proto3" json:"clientRegistry,omitempty"`
}

func (m *MsgUpdateClientRegistry) Reset()         { *m = MsgUpdateClientRegistry{} }
func (m *MsgUpdateClientRegistry) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateClientRegistry) ProtoMessage()    {}
func (*MsgUpdateClientRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d303193384f0350d, []int{4}
}
func (m *MsgUpdateClientRegistry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateClientRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateClientRegistry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateClientRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateClientRegistry.Merge(m, src)
}
func (m *MsgUpdateClientRegistry) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateClientRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateClientRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateClientRegistry proto.InternalMessageInfo

func (m *MsgUpdateClientRegistry) GetClientRegistry() *ClientRegistry {
	if m != nil {
		return m.ClientRegistry
	}
	return nil
}

type MsgUpdateClientRegistryResponse struct {
}

func (m *MsgUpdateClientRegistryResponse) Reset()         { *m = MsgUpdateClientRegistryResponse{} }
func (m *MsgUpdateClientRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateClientRegistryResponse) ProtoMessage()    {}
func (*MsgUpdateClientRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d303193384f0350d, []int{5}
}
func (m *MsgUpdateClientRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateClientRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateClientRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateClientRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateClientRegistryResponse.Merge(m, src)
}
func (m *MsgUpdateClientRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateClientRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateClientRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateClientRegistryResponse proto.InternalMessageInfo

type MsgDeleteClientRegistry struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgDeleteClientRegistry) Reset()         { *m = MsgDeleteClientRegistry{} }
func (m *MsgDeleteClientRegistry) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteClientRegistry) ProtoMessage()    {}
func (*MsgDeleteClientRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d303193384f0350d, []int{6}
}
func (m *MsgDeleteClientRegistry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteClientRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteClientRegistry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteClientRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteClientRegistry.Merge(m, src)
}
func (m *MsgDeleteClientRegistry) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteClientRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteClientRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteClientRegistry proto.InternalMessageInfo

func (m *MsgDeleteClientRegistry) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgDeleteClientRegistryResponse struct {
}

func (m *MsgDeleteClientRegistryResponse) Reset()         { *m = MsgDeleteClientRegistryResponse{} }
func (m *MsgDeleteClientRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteClientRegistryResponse) ProtoMessage()    {}
func (*MsgDeleteClientRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d303193384f0350d, []int{7}
}
func (m *MsgDeleteClientRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteClientRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteClientRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteClientRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteClientRegistryResponse.Merge(m, src)
}
func (m *MsgDeleteClientRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteClientRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteClientRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteClientRegistryResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgAuthenticationRequest)(nil), "beheroes.doxchain.idp.MsgAuthenticationRequest")
	proto.RegisterType((*MsgAuthenticationResponse)(nil), "beheroes.doxchain.idp.MsgAuthenticationResponse")
	proto.RegisterType((*MsgCreateClientRegistry)(nil), "beheroes.doxchain.idp.MsgCreateClientRegistry")
	proto.RegisterType((*MsgCreateClientRegistryResponse)(nil), "beheroes.doxchain.idp.MsgCreateClientRegistryResponse")
	proto.RegisterType((*MsgUpdateClientRegistry)(nil), "beheroes.doxchain.idp.MsgUpdateClientRegistry")
	proto.RegisterType((*MsgUpdateClientRegistryResponse)(nil), "beheroes.doxchain.idp.MsgUpdateClientRegistryResponse")
	proto.RegisterType((*MsgDeleteClientRegistry)(nil), "beheroes.doxchain.idp.MsgDeleteClientRegistry")
	proto.RegisterType((*MsgDeleteClientRegistryResponse)(nil), "beheroes.doxchain.idp.MsgDeleteClientRegistryResponse")
}

func init() { proto.RegisterFile("doxchain/idp/tx.proto", fileDescriptor_d303193384f0350d) }

var fileDescriptor_d303193384f0350d = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xbb, 0x4e, 0xf3, 0x30,
	0x14, 0x6e, 0xfe, 0xaa, 0xfd, 0x85, 0x91, 0x18, 0xa2, 0x16, 0x42, 0x86, 0x00, 0x91, 0x90, 0x60,
	0xc0, 0x81, 0x56, 0x62, 0x87, 0x32, 0x36, 0x4b, 0x24, 0x16, 0x16, 0x94, 0xcb, 0x91, 0x63, 0x28,
	0x76, 0x88, 0x5d, 0xa9, 0x5d, 0x78, 0x06, 0x1e, 0x8b, 0xb1, 0x23, 0x23, 0x6a, 0x9f, 0x80, 0x37,
	0x40, 0xcd, 0xa5, 0xa2, 0xe0, 0x44, 0xb0, 0xb0, 0xe5, 0xc4, 0xdf, 0x2d, 0xf9, 0xac, 0x83, 0xba,
	0x11, 0x9f, 0x84, 0xb1, 0x4f, 0x99, 0x43, 0xa3, 0xc4, 0x91, 0x13, 0x9c, 0xa4, 0x5c, 0x72, 0xbd,
	0x1b, 0x40, 0x0c, 0x29, 0x07, 0x81, 0xcb, 0x73, 0x4c, 0xa3, 0xc4, 0xec, 0x10, 0x4e, 0x78, 0x86,
	0x70, 0x96, 0x4f, 0x39, 0xd8, 0xb4, 0xd7, 0x34, 0xc2, 0x11, 0x05, 0x26, 0x6f, 0x53, 0x20, 0x54,
	0xc8, 0x74, 0x9a, 0x63, 0xec, 0x21, 0x32, 0x5c, 0x41, 0x2e, 0xc6, 0x32, 0x06, 0x26, 0x69, 0xe8,
	0x4b, 0xca, 0x99, 0x07, 0x8f, 0x63, 0x10, 0x52, 0x37, 0xd0, 0xff, 0x30, 0x05, 0x5f, 0xf2, 0xd4,
	0xd0, 0xf6, 0xb5, 0xa3, 0x0d, 0xaf, 0x1c, 0xf5, 0x6d, 0xd4, 0x96, 0xc0, 0x7c, 0x26, 0x8d, 0x7f,
	0xd9, 0x41, 0x31, 0xd9, 0x67, 0x68, 0x57, 0xa1, 0x26, 0x12, 0xce, 0x04, 0xe8, 0x1d, 0xd4, 0x92,
	0xfc, 0x1e, 0x58, 0x21, 0x96, 0x0f, 0x76, 0x8c, 0x76, 0x5c, 0x41, 0x06, 0x4b, 0x61, 0x18, 0x64,
	0x11, 0xbd, 0x22, 0xa1, 0xee, 0xa2, 0xad, 0x70, 0xed, 0x4d, 0xc6, 0xdc, 0xec, 0x1d, 0x62, 0xe5,
	0x5f, 0xc0, 0xeb, 0x74, 0xef, 0x0b, 0xd9, 0x3e, 0x40, 0x7b, 0x15, 0x4e, 0x65, 0xc4, 0x22, 0xcc,
	0x75, 0x12, 0xfd, 0x51, 0x18, 0x95, 0xd3, 0x2a, 0x4c, 0x3f, 0x0b, 0x73, 0x05, 0x23, 0xf8, 0x16,
	0xa6, 0xb2, 0x99, 0x42, 0x57, 0x45, 0x2a, 0x75, 0x7b, 0xef, 0x4d, 0xd4, 0x74, 0x05, 0xd1, 0xef,
	0x50, 0x6b, 0xc8, 0x09, 0x65, 0xba, 0x53, 0xf1, 0x09, 0x55, 0x17, 0xc3, 0x3c, 0xfd, 0x39, 0xa1,
	0xe8, 0xfe, 0x09, 0x75, 0x94, 0x15, 0xe3, 0x6a, 0x25, 0x15, 0xde, 0x3c, 0xff, 0x1d, 0xfe, 0xb3,
	0xbf, 0xb2, 0xd5, 0x1a, 0x7f, 0x15, 0xbe, 0xce, 0xbf, 0xae, 0xcb, 0xa5, 0xbf, 0xb2, 0xc8, 0x1a,
	0x7f, 0x15, 0xbe, 0xce, 0xbf, 0xae, 0xf3, 0xcb, 0xc1, 0xcb, 0xdc, 0xd2, 0x66, 0x73, 0x4b, 0x7b,
	0x9b, 0x5b, 0xda, 0xf3, 0xc2, 0x6a, 0xcc, 0x16, 0x56, 0xe3, 0x75, 0x61, 0x35, 0x6e, 0x8e, 0x09,
	0x95, 0xf1, 0x38, 0xc0, 0x21, 0x7f, 0x70, 0x02, 0x38, 0xc9, 0xc5, 0x9d, 0xd5, 0xe6, 0x98, 0xe4,
	0xfb, 0x67, 0x9a, 0x80, 0x08, 0xda, 0xd9, 0xca, 0xe8, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa7,
	0x9a, 0xd6, 0xa0, 0x9c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	Login(ctx context.Context, in *MsgAuthenticationRequest, opts ...grpc.CallOption) (*MsgAuthenticationResponse, error)
	CreateClientRegistry(ctx context.Context, in *MsgCreateClientRegistry, opts ...grpc.CallOption) (*MsgCreateClientRegistryResponse, error)
	UpdateClientRegistry(ctx context.Context, in *MsgUpdateClientRegistry, opts ...grpc.CallOption) (*MsgUpdateClientRegistryResponse, error)
	DeleteClientRegistry(ctx context.Context, in *MsgDeleteClientRegistry, opts ...grpc.CallOption) (*MsgDeleteClientRegistryResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Login(ctx context.Context, in *MsgAuthenticationRequest, opts ...grpc.CallOption) (*MsgAuthenticationResponse, error) {
	out := new(MsgAuthenticationResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.idp.Msg/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateClientRegistry(ctx context.Context, in *MsgCreateClientRegistry, opts ...grpc.CallOption) (*MsgCreateClientRegistryResponse, error) {
	out := new(MsgCreateClientRegistryResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.idp.Msg/CreateClientRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateClientRegistry(ctx context.Context, in *MsgUpdateClientRegistry, opts ...grpc.CallOption) (*MsgUpdateClientRegistryResponse, error) {
	out := new(MsgUpdateClientRegistryResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.idp.Msg/UpdateClientRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteClientRegistry(ctx context.Context, in *MsgDeleteClientRegistry, opts ...grpc.CallOption) (*MsgDeleteClientRegistryResponse, error) {
	out := new(MsgDeleteClientRegistryResponse)
	err := c.cc.Invoke(ctx, "/beheroes.doxchain.idp.Msg/DeleteClientRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	Login(context.Context, *MsgAuthenticationRequest) (*MsgAuthenticationResponse, error)
	CreateClientRegistry(context.Context, *MsgCreateClientRegistry) (*MsgCreateClientRegistryResponse, error)
	UpdateClientRegistry(context.Context, *MsgUpdateClientRegistry) (*MsgUpdateClientRegistryResponse, error)
	DeleteClientRegistry(context.Context, *MsgDeleteClientRegistry) (*MsgDeleteClientRegistryResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Login(ctx context.Context, req *MsgAuthenticationRequest) (*MsgAuthenticationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedMsgServer) CreateClientRegistry(ctx context.Context, req *MsgCreateClientRegistry) (*MsgCreateClientRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClientRegistry not implemented")
}
func (*UnimplementedMsgServer) UpdateClientRegistry(ctx context.Context, req *MsgUpdateClientRegistry) (*MsgUpdateClientRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClientRegistry not implemented")
}
func (*UnimplementedMsgServer) DeleteClientRegistry(ctx context.Context, req *MsgDeleteClientRegistry) (*MsgDeleteClientRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClientRegistry not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.idp.Msg/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Login(ctx, req.(*MsgAuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateClientRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateClientRegistry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateClientRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.idp.Msg/CreateClientRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateClientRegistry(ctx, req.(*MsgCreateClientRegistry))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateClientRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateClientRegistry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateClientRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.idp.Msg/UpdateClientRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateClientRegistry(ctx, req.(*MsgUpdateClientRegistry))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteClientRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteClientRegistry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteClientRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beheroes.doxchain.idp.Msg/DeleteClientRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteClientRegistry(ctx, req.(*MsgDeleteClientRegistry))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "beheroes.doxchain.idp.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Msg_Login_Handler,
		},
		{
			MethodName: "CreateClientRegistry",
			Handler:    _Msg_CreateClientRegistry_Handler,
		},
		{
			MethodName: "UpdateClientRegistry",
			Handler:    _Msg_UpdateClientRegistry_Handler,
		},
		{
			MethodName: "DeleteClientRegistry",
			Handler:    _Msg_DeleteClientRegistry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doxchain/idp/tx.proto",
}

func (m *MsgAuthenticationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAuthenticationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAuthenticationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAuthenticationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAuthenticationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAuthenticationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateClientRegistry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateClientRegistry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateClientRegistry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ClientRegistry != nil {
		{
			size, err := m.ClientRegistry.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateClientRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateClientRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateClientRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateClientRegistry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateClientRegistry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateClientRegistry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ClientRegistry != nil {
		{
			size, err := m.ClientRegistry.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateClientRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateClientRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateClientRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteClientRegistry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteClientRegistry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteClientRegistry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteClientRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteClientRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteClientRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgAuthenticationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAuthenticationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateClientRegistry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClientRegistry != nil {
		l = m.ClientRegistry.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateClientRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateClientRegistry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClientRegistry != nil {
		l = m.ClientRegistry.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateClientRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteClientRegistry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteClientRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgAuthenticationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAuthenticationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAuthenticationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAuthenticationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAuthenticationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAuthenticationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateClientRegistry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateClientRegistry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateClientRegistry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientRegistry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClientRegistry == nil {
				m.ClientRegistry = &ClientRegistry{}
			}
			if err := m.ClientRegistry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateClientRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateClientRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateClientRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateClientRegistry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateClientRegistry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateClientRegistry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientRegistry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClientRegistry == nil {
				m.ClientRegistry = &ClientRegistry{}
			}
			if err := m.ClientRegistry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateClientRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateClientRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateClientRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteClientRegistry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteClientRegistry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteClientRegistry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteClientRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteClientRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteClientRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
